carros = ['bmw', 'audi', 'toyota', 'subaru']
# carros.sort()
# carros.sort(reverse=True)
print("Here is the original list:")
print(carros)
print("\nHere is the sorted list:")
print(sorted(carros))
print("\nHere is the original list again:")
print(carros)
carros.reverse()
print(carros)